name: 'Auto Assign'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  add-reviews:
    permissions:
      pull-requests: write  
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: "Assign Team and Persons"
        uses: rowi1de/auto-assign-review-teams@v1.1.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          org: "ShareBookCode" #only needed for  pick-one-from-persons-or-team=true
          teams: "frontend-middle" # only works for GitHub Organisation/Teams
          include-draft: false # Draft PRs will be skipped (default: false)
          skip-with-manual-reviewers: 2 
          pick-one-from-persons-or-team: false # Will pick out one reviewer from persons and/or the first GitHub team and "org" set (default: false)