name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign random reviewers from teams
        uses: peter-evans/random-reviewer@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number-of-reviewers: 2
          teams: |
            frontend-middle
            frontend-junior