name: "Assign Random Reviewers"

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign random reviewer from Team A
        uses: ihs7/action-reviewer-roulette@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number-of-reviewers: 1
          teams: 'ShareBookCode/frontend-middle' 
          
      - name: Assign random reviewer from Team B
        uses: ihs7/action-reviewer-roulette@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number-of-reviewers: 1
          teams: 'ShareBookCode/frontend-junior'  
